name: Deployment
run-name: ${{ github.actor }}

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Connect to SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} <<EOF
            set -e
            cd ${{ secrets.APP_PATH }}
            git checkout master
            git pull
            sudo docker compose down
            sudo docker compose build
            sudo PORT=${{ secrets.APP_PORT }} docker compose up --remove-orphans -d
          EOF